# - name: Frontend Setup
#   hosts: FRONTEND
#   become: true 
#   roles: 
#     - frontend 

# - name: MongoDB Setup
#   hosts: MONGODB
#   become: true 
#   roles: 
#     - mongodb     

# - name: Catalogue Setup
#   hosts: CATALOGUE
#   become: true 
#   roles: 
#     - catalogue  

# - name: REDIS Setup
#   hosts: REDIS
#   become: true 
#   roles: 
#     - redis      


# - name: USER Setup
#   hosts: USER
#   become: true 
#   roles: 
#     - user  


# - name: CART Setup
#   hosts: CART
#   become: true 
#   roles: 
#     - cart           

# - name: MYSQL Setup
#   hosts: MYSQL
#   become: true 
#   roles: 
#     - mysql          


# - name: SHIPPING Setup
#   hosts: SHIPPING
#   become: true 
#   roles: 
#     - shipping      


- name: RABBITMQ
  hosts: RABBITMQ
  become: true 
  roles: 
    - rabbitmq          