- name: Demo on variables 
  hosts: all
  vars: 
    URL: play.example.com 
  tasks: 
    - name: Print Hello 
      ansible.builtin.debug: 
        msg: "Sweta - {{ URL}}"

- name: Demo on variables - from file
  hosts: webserver
  vars_files: 
    - sample-vars.yml  
  tasks: 
    - name: Print Hello 
      ansible.builtin.debug: 
        msg: "{{ URL}} - Kranti"   

- name: Demo on task level variables 
  hosts: webserver
  tasks: 
    - name: Print Hello 
      ansible.builtin.debug: 
        msg: "{{ URL}} - Suhasini"  
      vars: 
        URL: task.example.com    